---
date: "2024-09-22"
output: html_document
---

loading libraries and defining colors:
```{r}
rm(list = ls())

library(tidyverse)
library(plotly)
library(patchwork)
library(rlang)

# Color palette
media_colors <- c("#d69d10", "#000000", "#cc0000", "#05b2fc")
Sys.setlocale("LC_TIME", "en_US.UTF-8")
```


importing and cleaning data:
```{r}
# Updated function to process each data frame
process_frequency_data <- function(file_path, media_name) {
  df <- read_csv(file_path, show_col_types = FALSE)
  
  # Check the column names
  #print(colnames(df))
  
  df <- df %>%
    mutate(publish_date = as.Date(as.character(publish_date), format = "%Y%m%d")) %>%
    mutate(publish_month = format(publish_date, "%Y-%m")) %>%
    mutate(media = media_name) %>%
    arrange(publish_date, .by_group = TRUE)
}

# Apply the function with the updated folder path
AJ <- process_frequency_data("frequency_data_new/en_AJ_frequency.csv", "AJ")
BBC <- process_frequency_data("frequency_data_new/en_BBCNews_frequency.csv", "BBC")
CNN <- process_frequency_data("frequency_data_new/en_CNN_frequency.csv", "CNN")
DW <- process_frequency_data("frequency_data_new/en_DW_frequency.csv", "DW")
```
## combine data
```{r}
combined_channels <- rbind(AJ, BBC, CNN, DW)
```


## filter data
We only want the data after the 7th October
```{r}
combined_channels <- combined_channels %>% filter(publish_date > "2023-08-07")
```

```{r}
combined_channels <- combined_channels %>% filter(total_word_count > 20)
```


## function to filter calculate cumulative frequency
```{r}
add_accum <- function(Colname, df){
  # Check if the column exists in the data
  if (!(Colname %in% colnames(df))) {
    stop(paste("Column", Colname, "not found in combined_channels"))
  }

  # Filter for lemma
  combined_accum <- df %>%
    group_by(media) %>%
    mutate(acccum_freq = cumsum(.data[[Colname]])) %>%  # Use .data[[Colname]] to access the column by name
        mutate(rel_acccum_freq = cumsum(.data[[Colname]])/cumsum(total_word_count)* 1e6) %>%  # Use .data[[Colname]] to access the column by name
    mutate(count_max = max(acccum_freq)) %>%
    ungroup()
    
  
  return(combined_accum)
}
```

##creating function for plotting:
I changed the frequency to IPM:
(count_lemma / total_word_count) * 1e6) to account for differing video length
```{r}
plot_lemma <- function(lemma, date_to_plot) {
  # Plotting
  filtered_data <- add_accum(lemma, combined_channels)
  plot1 <- filtered_data %>%
    ggplot(aes(x = publish_date, y = acccum_freq, color = media)) +
    geom_line() +
    theme_minimal() +
    theme(panel.grid = element_blank(),
          axis.text.x = element_blank()) +
    #scale_y_log10() +
    scale_color_manual(values = media_colors) +
    xlab("") +
    ylab("cumulative frequency") +
    geom_vline(xintercept = as.Date(date_to_plot), linetype = "dashed") +
    labs(title = paste0("Mentions of ", lemma," in media"))

  plot2 <- filtered_data %>%
    #Relative accumulated Frequency:
    #ggplot(aes(x = publish_date, y = ((.data[[lemma]] / total_word_count) * 1e6), color=media, fill = media)) +
    #accumulated frequency
    #ggplot(aes(x = publish_date, y = (.data[[lemma]] ), color=media, group=media, fill = media)) +
    #accumulated frequency in IPM
    #ggplot(aes(x = publish_date, y = (.data[[lemma]] ), color=media, group=media, fill = media)) +
    ggplot(aes(x = publish_date, y = rel_acccum_freq, color = media)) +
    geom_line() +
    geom_vline(xintercept = as.Date(date_to_plot), linetype = "dashed") +
    scale_color_manual(values = media_colors) +
    theme_minimal() +
    theme(panel.grid = element_blank()) +
    scale_x_date(date_labels = "%B %Y", date_breaks = "1 month")+
    theme(
    axis.text.x = element_text(angle = 45, hjust = 1),  # Rotate x-axis labels
    #axis.line.x = element_line(color = "black"),        # Ensure x-axis line is drawn
    axis.ticks.x = element_line(color = "black")        # Ensure x-axis ticks are shown
    )+
    scale_fill_manual(values = media_colors) +
    xlab("")+ 
    ylab("relative \n cumulative frequency (ipm)")

  # Align the plots by a common X axis
  aligned_plots <- plot1 / plot2

  # Display the aligned plots
  print(aligned_plots)
}

```

plotting lemmas
```{r}
plot_lemma(lemma = "..genocide", 
           date_to_plot = c("2024-04-25", "2024-06-07"))
plot_lemma(lemma = "..Palestine", 
           date_to_plot = c("2024-04-25", "2024-06-07"))
plot_lemma(lemma = "..Israel", 
           date_to_plot = c("2024-04-25", "2024-06-07"))

plot_lemma(lemma = "..Hostage", 
           date_to_plot = c("2024-04-25", "2024-06-07"))

plot_lemma(lemma = "..Hamas", 
           date_to_plot = c("2024-04-25", "2024-06-07"))

plot_lemma(lemma = "..Terror", 
           date_to_plot = c("2024-04-25", "2024-06-07"))


plot_lemma(lemma = "Israelis..", 
           date_to_plot = c("2024-04-25", "2024-06-07"))
plot_lemma(lemma = "Palestinians..", 
           date_to_plot = c("2024-04-25", "2024-06-07"))
```


```{r}
plot_lemma_month <- function(lemma, date_to_plot) {
  # Plotting
combined_channels_month <- combined_channels %>%
  group_by(publish_month, media) %>%
  summarise(
    total_word_count = sum(ifelse(is.na(total_word_count), 0, total_word_count)),
    !!lemma := sum(.data[[lemma]], na.rm = TRUE),  # Dynamically assign column name
    #count_lemma = sum(count_lemma, na.rm = TRUE),  # Static column name
    .groups = 'drop'  # Drop group structure after summarising
  )
combined_channels_month$publish_month <- as.character(combined_channels_month$publish_month)
  filtered_data <- add_accum(lemma, combined_channels_month)
  print(head(filtered_data))
  plot1 <- filtered_data %>%
    ggplot(aes(x = publish_month, y = acccum_freq, color = media)) +
    #geom_point() +
    geom_line(aes(group=media))+
    theme_minimal() +
    theme(panel.grid = element_blank(),
          axis.text.x = element_blank()) +
    #scale_y_log10() +
    scale_color_manual(values = media_colors) +
    xlab("") +
    ylab("cumulative frequency") +
    #geom_vline(xintercept = as.Date(date_to_plot), linetype = "dashed") +
    labs(title = paste("Frequency of ", lemma," Mentions Across Various Media Outlets"))

  plot2 <- filtered_data %>%
    ggplot(aes(x = publish_month, y = ((.data[[lemma]] / total_word_count) * 1e6), fill = media)) +
   # geom_vline(xintercept = as.Date(date_to_plot), linetype = "dashed") +
    geom_col(position="dodge") +
    theme_minimal() +
    theme(panel.grid = element_blank()) +
    scale_y_continuous(labels = scales::comma) +
    scale_fill_manual(values = media_colors) +
    xlab("") +
    ylab("relative frequency \n (ipm)")+
            theme(
    axis.text.x = element_text(angle = 45, hjust = 1),  # Rotate x-axis labels
    #axis.line.x = element_line(color = "black"),        # Ensure x-axis line is drawn
    axis.ticks.x = element_line(color = "black")        # Ensure x-axis ticks are shown
    )

  # Align the plots by a common X axis
  aligned_plots <- plot1 / plot2

  # Display the aligned plots
  print(aligned_plots)
}

```

```{r}
plot_lemma_month(lemma = "..Terror", 
           date_to_plot = c("2024-04-25", "2024-06-07"))
```






